In [2]:
# Testing out tensorflow, more than anything

import tensorflow as tf

x = tf.Variable(3, name="one")
y = tf.Variable(3, name="two")
z = x*x*y + y + 2


/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [5]:
# Now we use the variables above
sess = tf.Session()
sess.run(x.initializer)
sess.run(y.initializer)
sess.run(z)

32

In [7]:
with tf.Session() as sess:
    x.initializer.run()
    y.initializer.run()
    result = z.eval()
    print (result)


32


In [ ]:
# Doing linear regression with TensorFlow

import tensorflow as tf
import numpy as np
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing(download_if_missing=False)


/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [1]:
with tf.Session() as sess:
    theta_value = theta.eval()
    print (theta_value)


NameError: name 'tf' is not defined

In [1]:
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing(download_if_missing=False)


In [2]:
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': 'California housing dataset.\n\nThe original database is available from StatLib\n\n 

In [3]:
import tensorflow as tf
import numpy as np
from sklearn.datasets import fetch_california_housing

m,n = housing.data.shape

housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

X = tf.constant(housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
Xt = tf.transpose(X)


/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(Xt, X)), Xt), y)

In [5]:
theta
intermediate = tf.matrix_inverse(tf.matmul(Xt, X))
with tf.Session() as sess:
    print(intermediate.eval())

[[ 8.3280170e-01  1.7330862e-03  1.4024429e-04 -1.6960822e-03
   4.9653235e-03  2.6645776e-07 -2.0582816e-05  8.0592949e-03
   9.4271358e-03]
 [ 1.7292782e-03  3.3596345e-05  3.6661200e-07 -3.5115801e-05
   1.5580961e-04  7.2289746e-10 -1.4578103e-07  2.3929504e-05
   2.2608423e-05]
 [ 1.4008376e-04  3.6694277e-07  3.7985012e-07  2.2102078e-07
  -4.9968071e-07  1.2947088e-09 -1.8697900e-08  1.5904914e-06
   1.7688019e-06]
 [-1.6910866e-03 -3.5112891e-05  2.2157481e-07  6.6045650e-05
  -2.9091924e-04  2.0295519e-09  1.1897595e-07 -2.5522480e-05
  -2.2474647e-05]
 [ 4.9407473e-03  1.5578012e-04 -5.0305511e-07 -2.9089939e-04
   1.5091239e-03 -1.7626423e-09 -5.0066774e-07  8.6477310e-05
   7.2613147e-05]
 [ 2.6473597e-07  7.2088191e-10  1.2944725e-09  2.0308690e-09
  -1.7621378e-09  4.2999104e-11 -3.5454825e-10  6.6607453e-09
   5.1119375e-09]
 [-2.0562160e-05 -1.4583246e-07 -1.8698287e-08  1.1905893e-07
  -5.0115784e-07 -3.5458267e-10  4.5291179e-07 -2.5852205e-07
  -2.4999403e-07]
 [ 8.0

In [6]:
with tf.Session() as sess:
    theta_value = theta.eval()
    print (theta_value)


[[-3.7185181e+01]
 [ 4.3633747e-01]
 [ 9.3952334e-03]
 [-1.0711310e-01]
 [ 6.4479220e-01]
 [-4.0338000e-06]
 [-3.7813708e-03]
 [-4.2348403e-01]
 [-4.3721911e-01]]


In [7]:
housing.feature_names


['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [9]:
# Let's scale the data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(housing_data_plus_bias)
scaled_housing_data = scaler.transform(housing_data_plus_bias)

print 

In [17]:

# Manually computing gradients
n_epochs = 10000
learning_rate = 0.0001

X = tf.constant(scaled_housing_data, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n+1, 1], -1, 1), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y

mse = tf. reduce_mean(tf.square(error), name="mse")
gradients = 2/m * tf.matmul(tf.transpose(X), error)
training_op = tf.assign(theta, theta - learning_rate * gradients)
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print ("Epoch ", epoch, ", MSE = ", mse.eval())
        sess.run(training_op)
        
    best_theta = theta.eval()
    print(best_theta)


Epoch  0 , MSE =  7.3372774
Epoch  100 , MSE =  7.230086
Epoch  200 , MSE =  7.1278553
Epoch  300 , MSE =  7.0303607
Epoch  400 , MSE =  6.937358
Epoch  500 , MSE =  6.8486342
Epoch  600 , MSE =  6.7639837
Epoch  700 , MSE =  6.6832075
Epoch  800 , MSE =  6.606114
Epoch  900 , MSE =  6.532536
Epoch  1000 , MSE =  6.4623046
Epoch  1100 , MSE =  6.3952537
Epoch  1200 , MSE =  6.3312426
Epoch  1300 , MSE =  6.2701106
Epoch  1400 , MSE =  6.2117352
Epoch  1500 , MSE =  6.155979
Epoch  1600 , MSE =  6.102724
Epoch  1700 , MSE =  6.0518456
Epoch  1800 , MSE =  6.003243
Epoch  1900 , MSE =  5.9567976
Epoch  2000 , MSE =  5.912422
Epoch  2100 , MSE =  5.8700066
Epoch  2200 , MSE =  5.8294697
Epoch  2300 , MSE =  5.7907214
Epoch  2400 , MSE =  5.7536798
Epoch  2500 , MSE =  5.7182627
Epoch  2600 , MSE =  5.6843977
Epoch  2700 , MSE =  5.652016
Epoch  2800 , MSE =  5.621048
Epoch  2900 , MSE =  5.5914273
Epoch  3000 , MSE =  5.5630927
Epoch  3100 , MSE =  5.535985
Epoch  3200 , MSE =  5.5100603


In [19]:
# The same code as above using auto-diff gradients which automatically compute
# the gradients of an unknown operation

n_epochs = 10000
learning_rate = 0.0001

X = tf.constant(scaled_housing_data, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n+1, 1], -1, 1), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y

mse = tf.reduce_mean(tf.square(error), name="mse")
gradients = tf.gradients(mse, [theta])[0]
training_op = tf.assign(theta, theta - learning_rate * gradients)
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print ("Epoch ", epoch, ", MSE = ", mse.eval())
        sess.run(training_op)
        
    best_theta = theta.eval()
    print(best_theta)



Epoch  0 , MSE =  8.48195
Epoch  100 , MSE =  8.254466
Epoch  200 , MSE =  8.042218
Epoch  300 , MSE =  7.8441586
Epoch  400 , MSE =  7.659307
Epoch  500 , MSE =  7.4867535
Epoch  600 , MSE =  7.3256497
Epoch  700 , MSE =  7.1752157
Epoch  800 , MSE =  7.0347066
Epoch  900 , MSE =  6.903458
Epoch  1000 , MSE =  6.780829
Epoch  1100 , MSE =  6.6662335
Epoch  1200 , MSE =  6.5591207
Epoch  1300 , MSE =  6.4589834
Epoch  1400 , MSE =  6.3653493
Epoch  1500 , MSE =  6.277785
Epoch  1600 , MSE =  6.1958666
Epoch  1700 , MSE =  6.1192217
Epoch  1800 , MSE =  6.047494
Epoch  1900 , MSE =  5.9803524
Epoch  2000 , MSE =  5.9174905
Epoch  2100 , MSE =  5.858621
Epoch  2200 , MSE =  5.8034787
Epoch  2300 , MSE =  5.7518163
Epoch  2400 , MSE =  5.703396
Epoch  2500 , MSE =  5.6580095
Epoch  2600 , MSE =  5.615456
Epoch  2700 , MSE =  5.5755453
Epoch  2800 , MSE =  5.538107
Epoch  2900 , MSE =  5.50298
Epoch  3000 , MSE =  5.4700084
Epoch  3100 , MSE =  5.4390526
Epoch  3200 , MSE =  5.4099846
Epoc

In [86]:
# And we can create the gradients automatically and also run gradient descent by
# running the GradientDescentOptimizer

from tensorflow.train import GradientDescentOptimizer
from datetime import datetime

# For tensorboard
now = datetime.utcnow().strftime("%Y%m%d%H%M%S")
root_logdir="tf_logs"
logdir="/tmp/{}/run-{}/".format(root_logdir, now)

n_epochs = 1000
learning_rate = 0.01
tf.reset_default_graph()

X = tf.constant(scaled_housing_data, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n+1, 1], -1, 1), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y

mse = tf.reduce_mean(tf.square(error), name="mse")
optimizer = GradientDescentOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(mse)
mse_summary=tf.summary.scalar('MSE', mse)
file_writer = tf.summary.FileWriter(logdir, tf.get_default_graph())

init = tf.global_variables_initializer()
saver = tf.train.Saver()


with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            summary_str = mse_summary.eval()
            step = epoch
            file_writer.add_summary(summary_str, step)
            print(mse.eval())

            # This was what we did for printing it out to stdout.
            #print ("Epoch ", epoch, ", MSE = ", mse.eval())
        sess.run(training_op)
        
    best_theta = theta.eval()
    print(best_theta)

    # And we can save this session once we are done.
    saver.save(sess, "/tmp/my_model_final.ckpt")
    
file_writer.close()

7.7486987
4.9461303
4.903606
4.879715
4.861981
4.848603
4.838457
4.8307214
4.8247957
4.8202343
[[-0.31000543]
 [ 0.8971107 ]
 [ 0.15766022]
 [-0.34393546]
 [ 0.34893757]
 [ 0.00877511]
 [-0.04405664]
 [-0.5528744 ]
 [-0.5290092 ]]


In [46]:
# Placeholders are used to fill data at run-time, and they are used to keep spots
# free for computation that can be filled up later.

# None signifies that this axes is unspecified.
A = tf.placeholder(tf.float32, shape=(None, None, None, 3))


In [47]:
A

<tf.Tensor 'Placeholder_5:0' shape=(?, ?, ?, 3) dtype=float32>

In [48]:
B = A + 5

with tf.Session() as s:
    B_1 = B.eval(feed_dict = {A: [[[[6 ,7, 4],[1, 2, 3]], [[6 ,7, 4],[1, 2, 3]]], [[[6 ,7, 4],[1, 2, 3]], [[6 ,7, 4],[1, 2, 3]]]]})
    print (B_1)
    
    #B_2 = B.eval(feed_dict = {A: [[],[], [1, 3, 4], [2, 3, 4]]})
    #print (B_2)

[[[[11. 12.  9.]
   [ 6.  7.  8.]]

  [[11. 12.  9.]
   [ 6.  7.  8.]]]


 [[[11. 12.  9.]
   [ 6.  7.  8.]]

  [[11. 12.  9.]
   [ 6.  7.  8.]]]]


In [72]:
housing.data.shape
housing.target.shape

sample_size=10000
#p = [i for i in range(sample_size)]
#print(p)

X = [[1, 2, 3 ], [4, 5, 6], [7, 8, 9]]
print(X[])

TypeError: list indices must be integers or slices, not tuple

In [ ]:
# Using placeholders, we can specify mini-batch gradient descent by sampling values into
# the matrix X and the values y.

from tensorflow.train import GradientDescentOptimizer

n_epochs = 4000
learning_rate = 0.001
sample_size=10000
# 8 features, and 1 intercept
feature_size=8

X = tf.placeholder(tf.float32, shape=(sample_size, 9), name="X")
y = tf.placeholder(tf.float32, shape=(sample_size, 1), name="y")


X = tf.constant(scaled_housing_data, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
# 8 features, and 1 intercept
theta = tf.Variable(tf.random_uniform([feature_size+1, 1], -1, 1), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y

mse = tf.reduce_mean(tf.square(error), name="mse")
optimizer = GradientDescentOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(mse)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(n_epochs):
        # Get a random distribution of sample_size rows from 1 to 20640
        indices = [i for i in range(sample_size)]

        # pick the rows of the housing_data matrix
        X
        if epoch % 100 == 0:
            print ("Epoch ", epoch, ", MSE = ", mse.eval())
        sess.run(training_op)
        
    best_theta = theta.eval()
    print(best_theta)

